Make the InstructionWriter put_xxx methods return a bool
meme/frida-rust pull request #14
Opened 2021-04-11 04:03 UTC by s1341

This is more in line with the gum api

2021-04-11 12:24 UTC, meme requested changes
LGTM, but fix CI/build errors please

2021-04-11 12:24 UTC, meme commented on frida-gum/src/instruction_writer.rs
>          println!("put_bytes: {:?}", bytes);
Please remove this `println!`, it slipped through

2021-04-16 10:52 UTC, s1341 commented
Done. Good to merge. Sorry for the delay.

2021-04-17 11:42 UTC, meme commented on frida-gum/src/instruction_writer.rs
> +            true
Interesting that x86 does not return a boolean but all other architectures do...

2021-04-17 11:42 UTC, meme approved these changes

2021-04-17 11:42 UTC, meme commented on frida-gum/src/instruction_writer.rs
> +            true
Interesting that x86 does not return a boolean but all other architectures do...

2021-04-17 11:43 UTC, merged